### ISSUE TITLE
Make Streamus' search input look like Google Inbox

### ISSUE THREAD

**Issue by ImBobby** [MeoMix/StreamusChromeExtension#400] opened 2015-01-30 12:27 UTC
Hi, first of all I like the product you made and I am more than happy to help/contribute as I could. I made some changes to the search input styles.

**Search input focused**
![search-input-focused](https://cloud.githubusercontent.com/assets/2084193/5975637/a5bec9f6-a8b5-11e4-852e-a5a2fe2e3913.png)

**Search input filled**
![search-input-filled](https://cloud.githubusercontent.com/assets/2084193/5975645/cb1fabf2-a8b5-11e4-9b33-2915ed5d5fe9.png)

How do you think of that?

**Comment by MeoMix** [comment] 2015-02-02 19:41
Hey,

This is a duplicate of #378 :) 

I do agree that it needs to look something like that. Here's how Google's looks: 

![image](https://cloud.githubusercontent.com/assets/1380995/6007629/779c67b4-aad0-11e4-8851-856100c8d110.png)

**Comment by ImBobby** [comment] 2015-02-03 09:15
But there's reason why the 'X' icon to be there right? It dismisses the search panel when user click on it. In my opinion, no need for that 'magnifying glass' icon, in exchange keep the 'X' icon.

**Comment by MeoMix** [comment] 2015-02-03 09:19
In my overall 'vision' of how it would look -- the magnifying glass would slide to the left as the search slides open and it would end up covering the 'playlist' button since you can only have one or the other open as it is.

Other concerns are just that there's no way to clear the text in the search input right now -- since 'X' closes the window entirely a lot of people who don't use ctrl+a + del to clear the search are left out to dry.

**Comment by csphere** [comment] 2015-02-03 10:01
Here's my input:

1. When user clicks the Streamus icon, autofocus the search box and give it maybe some more visual precedence and/or a very subtle pulsing animation to make it obvious it is focused.  It may seem weird at first, but the two use cases I see are:

	- Click streamus -> click on a button like 'play', 'pause', 'next', 'volume', etc. (which would unfocus the search box anyway)
	- Click streamus -> click on search, type something
	
	I don't see any reason not to assume the user will be searching off the bat as you could collapse the search box if they click a button other than the search icon/input.  Aesthetically, I love the animation idea you have with sliding the magnifying glass, but my favorite thing about Streamus is the speed of use.  Personally, I would gladly trade off some satisfying animations in order to save clicks or keystrokes.

2. When search input is opened and nothing is typed, show the 'X' icon and let it behave as it does now... but if the user has entered anything, replace the 'X' with an eraser icon.

	- If the eraser icon is shown and the user hits the ESC key, clear the text and show the 'X' icon.
	- If the eraser icon is shown and the user manually removes the search (ctrl-a, backspace, etc), then hide the eraser and show the 'X' again with current behavior.

I've been using it very heavily for the past week or two and it is amazing. Hands down my favorite music streaming software I have ever used.  <3  Thanks for all your work.

**Comment by MeoMix** [comment] 2015-05-11 00:52
Porting some comments over to #524

**Closed by MeoMix** 2015-05-11 00:52 UTC
