### ISSUE TITLE
Skip song if it has been made unavailable from youtube

### ISSUE THREAD

**Issue by poacher2k** [MeoMix/StreamusChromeExtension#469] opened 2015-03-11 11:43 UTC
Pausing and showing an error disrupts the experience, and causes the user to take unecessary actions to continue. If a song has been removed or made unavailable from YouTube, there's not much the user can do about that.
Suggestion: When coming to a song that is unavailable, skip to the next song. If user needs to be informed, give information inline in the playlist regarding the availability of the song.
![image](https://cloud.githubusercontent.com/assets/2255960/6595523/5cf3b5ce-c7eb-11e4-9438-99745b2058b0.png)

**Comment by poacher2k** [comment] 2015-03-11 11:44
Especially useful when playing a game, or doing something afk while listening to the music. As it is now, the user has to manually skip to next song and start playback.

**Comment by MeoMix** [comment] 2015-03-12 20:42
Closing, duplicate of #380

**Closed by MeoMix** 2015-03-12 20:42 UTC
