### ISSUE TITLE
Display a more meaningful error message when the song cannot be played because playing the video on other websites has been disabled by the uploader

### ISSUE THREAD

**Issue by silviubogan** [MeoMix/StreamusChromeExtension#407] opened 2015-02-04 10:57 UTC
For example [this song](https://www.youtube.com/watch?v=e-koQa5Eq90) cannot be played in Streamus and Streamus could show a more meaningful error message, maybe accompanied by a button to listen to the song on YouTube (by opening a new YouTube tab).

**Comment by MeoMix** [comment] 2015-02-04 20:38
Hey,

Duplicate of #293 

I've added a filter in for search results to make sure songs which can't be played in embedded players aren't shown in search results, but I agree the dialog should be better, too. YouTube just doesn't give me a lot of info on why the song could not be played. Just an error code which happens for a lot of different reasons.

**Closed by MeoMix** 2015-02-04 20:38 UTC
