### ISSUE TITLE
Sync playlist with youtube's copy

### ISSUE THREAD

**Issue by hypershadsy** [MeoMix/StreamusChromeExtension#429] opened 2015-02-15 23:53 UTC
I know you create a Streamus playlist and have it copy all tracks from a YouTube playlist. Why not extend this functionality so users don't have to update both manually?

"Sync" is a two-way word. That is, it describes

* when the Streamus playlist is changed, the YouTube playlist copies
* when the YouTube playlist is changed, the Streamus playlist copies

I personally only need one of these bullet points, but both would be appreciated.

**Comment by MeoMix** [comment] 2015-02-15 23:56
Closing, duplicate of #16

**Closed by MeoMix** 2015-02-15 23:56 UTC
