### ISSUE TITLE
Deleted songs should stay deleted

### ISSUE THREAD

**Issue by AlexFielder** [MeoMix/StreamusChromeExtension#379] opened 2015-01-23 16:13 UTC
Personally, I love the radio function, and I have a playlist I use to seed this, but when I delete a track (that I don't like, or don't want to listen to) if I then clear the queue and re-seed, I was wondering if there's a way for Streamus to remember what tracks have previously been deleted and prevent them from reappearing in the stream?

Otherwise, great work by the way!

**Comment by MeoMix** [comment] 2015-01-23 19:22
Hey,

It's certainly on the TODO list. I had implemented a 'Ban Song' method at one point in time, but, as you can see, the Stream and the Playlist aren't directly tied. I was clearing the ban list when the stream was cleared. This introduced confusion and the problem needed to be re-thought from the ground up, so I backed out of it. 

Closing this as it's a duplicate of #338

**Closed by MeoMix** 2015-01-23 19:22 UTC
